
package house_cleaning_booking_system;

import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    private Object JoptionPane;

    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginpanel = new javax.swing.JPanel();
        logintxt_username = new javax.swing.JLabel();
        login_username = new javax.swing.JTextField();
        logintxt_password = new javax.swing.JLabel();
        login_password = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ForgotPasswordButton = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOUSE CLEANING BOOKING SYSYTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "WELCOME TO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, 800, 121));

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 130));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        loginpanel.setBackground(new java.awt.Color(204, 204, 255));
        loginpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        loginpanel.setOpaque(false);
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintxt_username.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logintxt_username.setForeground(new java.awt.Color(255, 255, 255));
        logintxt_username.setText("USERNAME:");
        loginpanel.add(logintxt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        login_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginpanel.add(login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 320, 30));

        logintxt_password.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logintxt_password.setForeground(new java.awt.Color(255, 255, 255));
        logintxt_password.setText("PASSWORD:");
        loginpanel.add(logintxt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        login_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginpanel.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 320, 30));

        CreateButton.setBackground(new java.awt.Color(255, 255, 255));
        CreateButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(51, 51, 51));
        CreateButton.setText("CREATE ACCOUNT");
        CreateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        loginpanel.add(CreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("LOGIN");
        LoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        loginpanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 132, -1));

        jLabel2.setText("or");
        loginpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 19, -1));

        ForgotPasswordButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ForgotPasswordButton.setForeground(new java.awt.Color(51, 51, 255));
        ForgotPasswordButton.setText("forgot password");
        ForgotPasswordButton.setBorder(null);
        ForgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPasswordButtonActionPerformed(evt);
            }
        });
        loginpanel.add(ForgotPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 830, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
    
        if (logintxt_username.getText().equals(" ")){
            JOptionPane.showMessageDialog(null, "Please fill out username:");
        } else if (logintxt_password.getText().equals(" ")) {
           JOptionPane.showMessageDialog(null, "Please fill out username:"); 
        
        } else if (login_password.getText().equals("xhinsade123") && login_password.getText().contains("xhinsade123")) {
           JOptionPane.showMessageDialog(null, "You have successfully Login");
           HomePage1 home = new HomePage1();
           home.setVisible(true);
           this.dispose();
        } else if (!login_password.getText().equals("xhinsade123") && !login_password.getText().contains("xhinsade123")) {
            JOptionPane.showMessageDialog(null,"You have enter incorrect username or password!!", "Message",JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"Please fill out the username or password!!", "Message",JOptionPane.ERROR_MESSAGE);
         
    }//GEN-LAST:event_LoginButtonActionPerformed
    }
    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        CREATE_ACCOUNT create = new CREATE_ACCOUNT();
        create.setVisible(true);
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void ForgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPasswordButtonActionPerformed
     RESET_PASSWORD reset = new RESET_PASSWORD();
     reset.setVisible(true);
    }//GEN-LAST:event_ForgotPasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton ForgotPasswordButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField login_password;
    private javax.swing.JTextField login_username;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel logintxt_password;
    private javax.swing.JLabel logintxt_username;
    // End of variables declaration//GEN-END:variables
}
